/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package app;
//import hexlet.code.App;
import hexlet.code.Differ;
import hexlet.code.FileReader;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {

    @Test
    void appJsonDifferGenerateStylish() throws Exception {
        String filepath1 = "src/test/resources/fixtures/file1_1.json";
        String filepath2 = "src/test/resources/fixtures/file2_2.json";
        String filepath3 = "src/test/resources/fixtures/stylish.txt";
        String format = "stylish";
        String result = FileReader.getDataFromFile(filepath3);
        String diff = Differ.generate(filepath1, filepath2, format);
        assertEquals(diff, result);
    }

    @Test
    void appYmlDifferGenerateStylish() throws Exception {
        String filepath1 = "src/test/resources/fixtures/file1_1.yml";
        String filepath2 = "src/test/resources/fixtures/file2_2.yml";
        String filepath3 = "src/test/resources/fixtures/stylish.txt";
        String format = "stylish";
        String result = FileReader.getDataFromFile(filepath3);
        String diff = Differ.generate(filepath1, filepath2, format);
        assertEquals(diff, result);
    }

    @Test
    void appJsonDifferGeneratePlain() throws Exception {
        String filepath1 = "src/test/resources/fixtures/file1_1.json";
        String filepath2 = "src/test/resources/fixtures/file2_2.json";
        String filepath3 = "src/test/resources/fixtures/plain.txt";
        String format = "plain";
        String result = FileReader.getDataFromFile(filepath3);
        String diff = Differ.generate(filepath1, filepath2, format);
        assertEquals(diff, result);
    }

    @Test
    void appYmlDifferGeneratePlain() throws Exception {
        String filepath1 = "src/test/resources/fixtures/file1_1.yml";
        String filepath2 = "src/test/resources/fixtures/file2_2.yml";
        String filepath3 = "src/test/resources/fixtures/plain.txt";
        String format = "plain";
        String result = FileReader.getDataFromFile(filepath3);
        String diff = Differ.generate(filepath1, filepath2, format);
        assertEquals(diff, result);
    }

    @Test
    void appJsonDifferGenerateJson() throws Exception {
        String filepath1 = "src/test/resources/fixtures/file1_1.json";
        String filepath2 = "src/test/resources/fixtures/file2_2.json";
        String filepath3 = "src/test/resources/fixtures/json.txt";
        String format = "json";
        String result = FileReader.getDataFromFile(filepath3);
        String diff = Differ.generate(filepath1, filepath2, format);
        assertEquals(diff, result);
    }

    @Test
    void appYmlDifferGenerateJson() throws Exception {
        String filepath1 = "src/test/resources/fixtures/file1_1.yml";
        String filepath2 = "src/test/resources/fixtures/file2_2.yml";
        String filepath3 = "src/test/resources/fixtures/json.txt";
        String format = "json";
        String result = FileReader.getDataFromFile(filepath3);
        String diff = Differ.generate(filepath1, filepath2, format);
        assertEquals(diff, result);
    }
}
