name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        #run: make build
        #with:
        #  super_secret: ${{ secrets.SUPERSECRET }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
       #- name: Publish code coverage
       #  uses: paambaati/codeclimate-action@v3.0.0
       #  env:
       #    CC_TEST_REPORTER_ID: f75224f824f52a079befff79dcb22ea2b5e9f68faf979c7784db640b53e78435
       #    JACOCO_SOURCE_PATH: src/main/java
       #  with:
       #    coverageCommand: make report
       #    coverageLocations: https://github.com/EEFIMOVA2021/java-project-lvl1/build/reports/jacoco/test/jacocoTestReport.xml:jacoco